baseURL = "https://www.halalmuintb.org"
languageCode = "en-us"
paginate = 6
summaryLength = "10"
theme = "influencer-hugo"
title = "Halal MUI NTB"
[menu.main]
URL = "book"
name = "Beranda"
weight = 1
[params]
author = "Themefisher"
copyright = "Copyright &copy; 2021 LPPOM MUI NTB All Rights Reserved"
description = "This is meta description"
googleAnalitycsID = ""
home = "Home"
logo = "/uploads/logo_halal.png"
[params.cookies]
enable = true
expire_days = "1"
[params.footer]
content = "Lembaga Pemeriksa Halal (LPH) yang amanah untuk ummat Islam di seluruh Indonesia khususnya di Nusa Tenggara Barat dan selalu menjadi yang terdepan dalam solusi Jaminan Halal."
[params.navButton]
enable = true
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/magnific-popup.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.share]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.share]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.share]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
[[params.share]]
icon = "ti-github"
link = "#"
title = "github"
